# Environment / PATH (managed by chezmoi)

export EDITOR="code --wait"

# PATH basics
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/src/scripts:$PATH"

# ---- completions dir ----
ZSH_COMPLETIONS_DIR="$HOME/.config/zsh/completions"
mkdir -p "$ZSH_COMPLETIONS_DIR" 2>/dev/null || true
fpath=("$ZSH_COMPLETIONS_DIR" $fpath)

# ---- zsh completion (core) ----
# Ensure zsh's Completion functions are on fpath (macOS ships them in a subdir)
if [[ -d "/usr/share/zsh/${ZSH_VERSION}/functions/Completion" ]]; then
  fpath=(/usr/share/zsh/${ZSH_VERSION}/functions/Completion $fpath)
elif [[ -d "/usr/share/zsh/functions/Completion" ]]; then
  fpath=(/usr/share/zsh/functions/Completion $fpath)
fi

autoload -Uz compinit
compinit -C

# ---- zsh plugins (loaders) ----
for f in "$HOME/.config/zsh/plugins.d/"*.zsh(N); do
  source "$f"
done

# 1Password SSH agent socket (macOS; harmless elsewhere if path missing)
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

# Rust
[[ -r "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# Homebrew OpenSSL hint (only if brew exists)
if command -v brew >/dev/null 2>&1; then
  export OPENSSL_ROOT_DIR="$(brew --prefix openssl@3 2>/dev/null)"
fi

# 1Password CLI shell plugins (load once, if present)
[[ -r "$HOME/.config/op/plugins.sh" ]] && source "$HOME/.config/op/plugins.sh"

# fzf bindings/completion (generated by brew fzf install)
[[ -r "$HOME/.fzf.zsh" ]] && source "$HOME/.fzf.zsh"