# Environment / PATH (managed by chezmoi)

export EDITOR="code --wait"

# PATH basics
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/src/scripts:$PATH"

# 1Password SSH agent socket (macOS; harmless elsewhere if path missing)
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

# Rust
[[ -r "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# Homebrew OpenSSL hint (only if brew exists)
if command -v brew >/dev/null 2>&1; then
  export OPENSSL_ROOT_DIR="$(brew --prefix openssl@3 2>/dev/null)"
fi

# 1Password CLI shell plugins (load once, if present)
[[ -r "$HOME/.config/op/plugins.sh" ]] && source "$HOME/.config/op/plugins.sh"

# fzf bindings/completion (generated by brew fzf install)
[[ -r "$HOME/.fzf.zsh" ]] && source "$HOME/.fzf.zsh"