# Environment / PATH (managed by chezmoi)

export EDITOR="code --wait"

# PATH basics
export PATH="$HOME/.local/bin:$PATH"
export PATH="$HOME/src/scripts:$PATH"

# ---- fzf defaults ----
export FZF_DEFAULT_OPTS="
  --height=40%
  --layout=reverse
  --border
  --inline-info
"

# Use fd if available (faster, respects .gitignore-ish behavior)
if command -v fd >/dev/null 2>&1; then
  export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
  export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
fi

# fzf bindings/completion (generated by brew fzf install)
[[ -r "$HOME/.fzf.zsh" ]] && source "$HOME/.fzf.zsh"

# Fuzzy git branch checkout
gcof() {
  local b
  b="$(
    git branch --all --format='%(refname:short)' 2>/dev/null \
      | sed '/^HEAD$/d' \
      | sed '/->/d' \
      | fzf
  )" || return
  git checkout "$b"
}

# ---- completions dir ----
ZSH_COMPLETIONS_DIR="$HOME/.config/zsh/completions"
mkdir -p "$ZSH_COMPLETIONS_DIR" 2>/dev/null || true
fpath=("$ZSH_COMPLETIONS_DIR" $fpath)

# ---- zsh completion (core) ----
# Ensure zsh's Completion functions are on fpath (macOS ships them in a subdir)
if [[ -d "/usr/share/zsh/${ZSH_VERSION}/functions/Completion" ]]; then
  fpath=(/usr/share/zsh/${ZSH_VERSION}/functions/Completion $fpath)
elif [[ -d "/usr/share/zsh/functions/Completion" ]]; then
  fpath=(/usr/share/zsh/functions/Completion $fpath)
fi

# Homebrew completions (if available)
if command -v brew >/dev/null 2>&1; then
  fpath=(
    "$(brew --prefix)/share/zsh/site-functions"
    "$(brew --prefix)/share/zsh-completions"
    $fpath
  )
fi

autoload -Uz compinit
ZSH_COMPDUMP="${XDG_CACHE_HOME:-$HOME/.cache}/zsh/zcompdump"
mkdir -p "${ZSH_COMPDUMP:h}" 2>/dev/null || true
compinit -C -d "$ZSH_COMPDUMP"

#-------------------------------------------------------------------------------
#---- most settings should come after this line! -------------------------------
#-------------------------------------------------------------------------------

# ---- word/path semantics ----
# Make "word" jumps behave like path/arg jumps (/, -, ., _ become boundaries)
WORDCHARS=''

# ---- Option+Arrow / Option+Delete word ops (portable) ----
for km in emacs viins; do
  # Move by word
  bindkey -M $km '^[b'      backward-word   # Meta-b (common)
  bindkey -M $km '^[f'      forward-word    # Meta-f (common)
  bindkey -M $km '^[[1;9D'  backward-word   # ⌥← (iTerm2 variant)
  bindkey -M $km '^[[1;9C'  forward-word    # ⌥→ (iTerm2 variant)
  bindkey -M $km '^[[1;3D'  backward-word   # ⌥← (alt variant)
  bindkey -M $km '^[[1;3C'  forward-word    # ⌥→ (alt variant)

  # Delete word backward (⌥⌫)
  bindkey -M $km '^[^?'     backward-kill-word
  bindkey -M $km '^[^H'     backward-kill-word
  bindkey -M $km '^[\b'     backward-kill-word

  # Delete word forward (⌥⌦)
  bindkey -M $km '^[[3;3~'  kill-word
  bindkey -M $km '^[[3;9~'  kill-word
done

# ---- completion UX: don't destroy my buffer ----
unsetopt MENU_COMPLETE          # don't replace text by cycling matches
setopt AUTO_MENU               # show menu when there are multiple matches
setopt COMPLETE_IN_WORD        # complete from cursor, not just end
setopt ALWAYS_TO_END           # move cursor to end after completion
setopt NO_BEEP                 # stop yelling at me

# Make selection explicit when there are many matches
zstyle ':completion:*' menu select
zstyle ':completion:*' group-name ''
zstyle ':completion:*:descriptions' format '%d'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format '%d'

# ---- zsh plugins (loaders) ----
for f in "$HOME/.config/zsh/plugins.d/"*.zsh(N); do
  source "$f"
done

# 1Password SSH agent socket (macOS; harmless elsewhere if path missing)
export SSH_AUTH_SOCK="$HOME/Library/Group Containers/2BUA8C4S2C.com.1password/t/agent.sock"

# Rust
[[ -r "$HOME/.cargo/env" ]] && source "$HOME/.cargo/env"

# Homebrew OpenSSL hint (only if brew exists)
if command -v brew >/dev/null 2>&1; then
  export OPENSSL_ROOT_DIR="$(brew --prefix openssl@3 2>/dev/null)"
fi

# 1Password CLI shell plugins (load once, if present)
[[ -r "$HOME/.config/op/plugins.sh" ]] && source "$HOME/.config/op/plugins.sh"

