[".config/zsh/plugins/fzf-tab"]
type = "git-repo"
url = "https://github.com/Aloxaf/fzf-tab.git"
refreshPeriod = "168h"

[".config/zsh/plugins/fzf-tab-source"]
type = "git-repo"
url = "https://github.com/Freed-Wu/fzf-tab-source.git"
refreshPeriod = "168h"

[".config/tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
refreshPeriod = "168h"