tap "homebrew/bundle"

brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "git"
brew "bat"
brew "duti"
brew "git-delta"
brew "gh"
brew "ghq"
brew "glow"
brew "chafa"
brew "ripgrep"
brew "less"
brew "fzf"
brew "fd"
brew "eza"
brew "zoxide"
brew "starship"
brew "mosh"
brew "micro"
brew "navi"
brew "tealdeer"
brew "uv"

cask "windows-app"
cask "visual-studio-code@insiders"
