tap "homebrew/bundle"

brew "zsh-completions"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "git"
brew "bat"
brew "git-delta"
brew "gh"
brew "ghq"
brew "glow"
brew "chafa"
brew "ripgrep"
brew "less"
brew "fzf"
brew "eza"
brew "zoxide"
brew "starship"
