#!/usr/bin/env bash
set -euo pipefail

# full.sh — Complete machine setup (all-in-one)
# Use this for a complete setup with dotfiles and all tools
# Requires: GitHub access to private dotfiles repo
# Assumes: You're setting up a new machine or ready to overwrite config
#
# Generated from: dotfiles/scripts/templates/full.sh.template
# DO NOT EDIT THIS FILE DIRECTLY — edit the template in dotfiles repo

log() { printf "[full] %s\n" "$*"; }
need_cmd() { command -v "$1" >/dev/null 2>&1; }

DOTFILES_REPO="${DOTFILES_REPO:-https://github.com/mkhnsn/dotfiles.git}"

log "Starting full machine setup"

# ─────────────────────────────────────────────────────────────
# Detect OS
# ─────────────────────────────────────────────────────────────

case "$(uname -s)" in
  Darwin) OS="darwin" ;;
  Linux)  OS="linux"  ;;
  *)      echo "Unsupported OS" >&2; exit 1 ;;
esac

log "Detected OS: $OS"

# ─────────────────────────────────────────────────────────────
# Install system prerequisites
# ─────────────────────────────────────────────────────────────

log "Installing system prerequisites"

if [[ "$OS" == "linux" ]]; then
  if need_cmd apt-get; then
    log "Using apt-get"
    sudo apt-get update -y
    sudo apt-get install -y git curl ca-certificates zsh
  elif need_cmd dnf; then
    log "Using dnf"
    sudo dnf install -y git curl ca-certificates zsh
  elif need_cmd yum; then
    log "Using yum"
    sudo yum install -y git curl ca-certificates zsh
  elif need_cmd pacman; then
    log "Using pacman"
    sudo pacman -Sy --noconfirm git curl ca-certificates zsh
  else
    log "ERROR: No supported package manager found"
    log "Supported: apt-get, dnf, yum, pacman"
    exit 1
  fi
else
  # macOS: ensure Xcode CLT
  if ! need_cmd git; then
    log "Installing Xcode Command Line Tools"
    xcode-select --install >/dev/null 2>&1 || true
    # Wait for install to complete
    while ! command -v git >/dev/null 2>&1; do
      log "Waiting for Xcode CLT installation..."
      sleep 5
    done
  fi
fi

log "✓ System prerequisites installed"

# ─────────────────────────────────────────────────────────────
# Validate dotfiles repo access (early check)
# ─────────────────────────────────────────────────────────────

log "Validating access to dotfiles repository"

if ! git ls-remote "$DOTFILES_REPO" HEAD >/dev/null 2>&1; then
  log "ERROR: Cannot access dotfiles repository"
  log ""
  log "Repository: $DOTFILES_REPO"
  log ""
  log "Possible causes:"
  log "  • You don't have GitHub access to the private repo"
  log "  • SSH key not set up"
  log "  • Network connectivity issue"
  log ""
  log "To set up SSH:"
  log "  ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519"
  log "  ssh-add ~/.ssh/id_ed25519"
  log "  ssh -T git@github.com  # Test connection"
  log ""
  exit 1
fi

log "✓ Repository access confirmed"

# ─────────────────────────────────────────────────────────────
# macOS: Install Homebrew
# ─────────────────────────────────────────────────────────────

if [[ "$OS" == "darwin" ]]; then
  if ! need_cmd brew; then
    log "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    eval "$(/opt/homebrew/bin/brew shellenv)"
  else
    log "Homebrew already installed"
  fi
fi

# ─────────────────────────────────────────────────────────────
# Install chezmoi
# ─────────────────────────────────────────────────────────────

log "Installing chezmoi"

if ! need_cmd chezmoi; then
  if [[ "$OS" == "darwin" ]]; then
    if [[ -w /usr/local/bin ]]; then
      sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
    else
      mkdir -p "$HOME/.local/bin"
      sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"
      export PATH="$HOME/.local/bin:$PATH"
    fi
  else
    sudo sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
  fi
else
  log "chezmoi already installed"
fi

# ─────────────────────────────────────────────────────────────
# Apply dotfiles
# ─────────────────────────────────────────────────────────────

log "Applying dotfiles"

chezmoi init --apply "$DOTFILES_REPO"

# ─────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────

log "✓ Setup complete!"
log ""
log "You now have:"
log "  • System prerequisites"
log "  • chezmoi installed"
log "  • Dotfiles applied (all config, tools, and packages)"
log ""
log "Start a new shell to apply all changes: exec zsh"
log ""
