#!/usr/bin/env bash
set -euo pipefail

# full.sh — Complete machine setup (all-in-one)
# Use this for a complete setup with dotfiles and all tools
# Requires: GitHub access to private dotfiles repo
# Assumes: You're setting up a new machine or ready to overwrite config
#
# Generated from: dotfiles/scripts/templates/full.sh.template
# DO NOT EDIT THIS FILE DIRECTLY — edit the template in dotfiles repo

# --- Safety guards ------------------------------------------------------------

die() { echo "[full] ERROR: $*" >&2; exit 1; }
log() { printf "[full] %s\n" "$*"; }
need_cmd() { command -v "$1" >/dev/null 2>&1; }
is_interactive() { [[ -t 1 ]]; }

# Non-interactive SSH for git checks (fail fast instead of hanging)
# - BatchMode=yes: never prompt for passwords/passphrases
# - ConnectTimeout: short timeout
# - StrictHostKeyChecking=accept-new: non-interactive first-connect (safe enough for bootstrap)
GIT_SSH_COMMAND_DEFAULT="ssh -o BatchMode=yes -o ConnectTimeout=5 -o StrictHostKeyChecking=accept-new"

# Refuse to run as root (too easy to clobber $HOME and permissions)
if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
  die "Do not run as root. Run as your normal user; this script uses sudo when needed."
fi

DOTFILES_REPO="${DOTFILES_REPO:-git@github.com:mkhnsn/dotfiles.git}"

log "Starting full machine setup"

is_in_dotfiles_repo() {
  # Git remote heuristic (most reliable)
  if command -v git >/dev/null 2>&1 && git rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    git remote -v 2>/dev/null | grep -Eq 'mkhnsn/dotfiles(\.git)?' && return 0
  fi

  # Heuristic fallback: common markers in your dotfiles repo root
  [[ -f ".chezmoiexternal.toml" ]] && return 0
  [[ -d "dot_config" ]] && return 0
  [[ -f "dot_zshrc" ]] && return 0

  return 1
}

has_existing_chezmoi_source() {
  command -v chezmoi >/dev/null 2>&1 || return 1
  local sp
  sp="$(chezmoi source-path 2>/dev/null || true)"
  [[ -n "$sp" && -d "$sp" ]]
}

# Refuse to run from inside the dotfiles working copy
if is_in_dotfiles_repo; then
  die "Refusing to run from inside the dotfiles repo. Run 'chezmoi apply' or 'chezmoi update' instead."
fi

# If chezmoi is already initialized, treat this as an idempotent re-run.
# This avoids re-initializing and reduces the chance of clobbering a working setup.
if has_existing_chezmoi_source; then
  log "Existing chezmoi source detected; running idempotent update instead of init"
  export DOTFILES_FULL=1
  chezmoi update
  log "✓ Update complete"
  exit 0
fi

# ─────────────────────────────────────────────────────────────
# Detect OS
# ─────────────────────────────────────────────────────────────

case "$(uname -s)" in
  Darwin) OS="darwin" ;;
  Linux)  OS="linux"  ;;
  *)      echo "Unsupported OS" >&2; exit 1 ;;
esac

log "Detected OS: $OS"

# ─────────────────────────────────────────────────────────────
# Install system prerequisites
# ─────────────────────────────────────────────────────────────

log "Installing system prerequisites"

if [[ "$OS" == "linux" ]]; then
  if need_cmd apt-get; then
    log "Using apt-get"
    sudo apt-get update -y
    sudo apt-get install -y git curl ca-certificates zsh
  elif need_cmd dnf; then
    log "Using dnf"
    sudo dnf install -y git curl ca-certificates zsh
  elif need_cmd yum; then
    log "Using yum"
    sudo yum install -y git curl ca-certificates zsh
  elif need_cmd pacman; then
    log "Using pacman"
    sudo pacman -Sy --noconfirm git curl ca-certificates zsh
  else
    log "ERROR: No supported package manager found"
    log "Supported: apt-get, dnf, yum, pacman"
    exit 1
  fi
else
  # macOS: ensure Xcode Command Line Tools
  if ! xcode-select -p >/dev/null 2>&1; then
    log "Installing Xcode Command Line Tools (interactive prompt may appear)"
    xcode-select --install >/dev/null 2>&1 || true

    # Give the installer a chance; don't spin forever.
    for i in {1..120}; do
      if xcode-select -p >/dev/null 2>&1; then
        break
      fi
      log "Waiting for Xcode CLT installation... ($i/120)"
      sleep 5
    done

    if ! xcode-select -p >/dev/null 2>&1; then
      die "Xcode Command Line Tools not detected yet. Finish the install, then rerun this script."
    fi
  fi

  # git should now be available, but check explicitly
  if ! need_cmd git; then
    die "git is still not available after CLT check. Open Xcode CLT installer, complete it, then rerun."
  fi
fi

log "✓ System prerequisites installed"

# ─────────────────────────────────────────────────────────────
# Validate dotfiles repo access (early check)
# ─────────────────────────────────────────────────────────────

log "Validating access to dotfiles repository"

if ! env GIT_SSH_COMMAND="${GIT_SSH_COMMAND:-$GIT_SSH_COMMAND_DEFAULT}" git ls-remote "$DOTFILES_REPO" HEAD >/dev/null 2>&1; then
  log "ERROR: Cannot access dotfiles repository"
  log ""
  log "Repository: $DOTFILES_REPO"
  log ""
  log "Possible causes:"
  log "  • You don't have GitHub access to the private repo"
  log "  • SSH key not set up"
  log "  • Network connectivity issue"
  log ""
  log "To set up SSH access to GitHub:"
  log "  1) Ensure you have an SSH key and it's added to your agent:"
  log "     ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519"
  log "     ssh-add ~/.ssh/id_ed25519"
  log "  2) Add the public key to GitHub → Settings → SSH and GPG keys:"
  log "     cat ~/.ssh/id_ed25519.pub"
  log "  3) Test connection:"
  log "     ssh -o BatchMode=yes -o ConnectTimeout=5 -T git@github.com"
  log ""
  exit 1
fi

log "✓ Repository access confirmed"

# ─────────────────────────────────────────────────────────────
# macOS: Install Homebrew
# ─────────────────────────────────────────────────────────────

if [[ "$OS" == "darwin" ]]; then
  if ! need_cmd brew; then
    log "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    if [[ -x "/opt/homebrew/bin/brew" ]]; then
      eval "$(/opt/homebrew/bin/brew shellenv)"
    elif [[ -x "/usr/local/bin/brew" ]]; then
      eval "$(/usr/local/bin/brew shellenv)"
    fi
  else
    log "Homebrew already installed"
  fi
fi

# ─────────────────────────────────────────────────────────────
# Install chezmoi
# ─────────────────────────────────────────────────────────────

log "Installing chezmoi"

if ! need_cmd chezmoi; then
  if [[ "$OS" == "darwin" ]]; then
    if [[ -w /usr/local/bin ]]; then
      sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
    else
      mkdir -p "$HOME/.local/bin"
      sh -c "$(curl -fsLS get.chezmoi.io)" -- -b "$HOME/.local/bin"
      export PATH="$HOME/.local/bin:$PATH"
    fi
  else
    sudo sh -c "$(curl -fsLS get.chezmoi.io)" -- -b /usr/local/bin
  fi
else
  log "chezmoi already installed"
fi

# ─────────────────────────────────────────────────────────────
# Apply dotfiles
# ─────────────────────────────────────────────────────────────

export DOTFILES_FULL=1
chezmoi init --apply "$DOTFILES_REPO"

# ─────────────────────────────────────────────────────────────
# Done
# ─────────────────────────────────────────────────────────────

log "✓ Setup complete!"
log ""
log "You now have:"
log "  • System prerequisites"
log "  • chezmoi installed"
log "  • Dotfiles applied (all config, tools, and packages)"
log ""
log "Start a new shell to apply all changes: exec zsh  (or restart your terminal)"
log ""
