#!/usr/bin/env bash
set -euo pipefail

# minimal.sh — Standalone bootstrap to a working shell
# No dependencies. No private repo access required.
# Works on any machine, gets you to a usable shell environment.
#
# Generated from: dotfiles/scripts/templates/minimal.sh.template
# DO NOT EDIT THIS FILE DIRECTLY — edit the template in dotfiles repo

log() { printf "[minimal] %s\n" "$*"; }
need_cmd() { command -v "$1" >/dev/null 2>&1; }

log "Starting minimal bootstrap"

# ─────────────────────────────────────────────────────────────
# Detect OS
# ─────────────────────────────────────────────────────────────

case "$(uname -s)" in
  Darwin) OS="darwin" ;;
  Linux)  OS="linux"  ;;
  *)      echo "Unsupported OS" >&2; exit 1 ;;
esac

log "Detected OS: $OS"

# ─────────────────────────────────────────────────────────────
# Install system prerequisites
# ─────────────────────────────────────────────────────────────

log "Installing system prerequisites"

if [[ "$OS" == "linux" ]]; then
  if need_cmd apt-get; then
    log "Using apt-get"
    sudo apt-get update -y
    sudo apt-get install -y git curl ca-certificates zsh
  elif need_cmd dnf; then
    log "Using dnf"
    sudo dnf install -y git curl ca-certificates zsh
  elif need_cmd yum; then
    log "Using yum"
    sudo yum install -y git curl ca-certificates zsh
  elif need_cmd pacman; then
    log "Using pacman"
    sudo pacman -Sy --noconfirm git curl ca-certificates zsh
  else
    log "ERROR: No supported package manager found"
    log "Supported: apt-get, dnf, yum, pacman"
    exit 1
  fi
else
  # macOS: ensure Xcode CLT
  if ! need_cmd git; then
    log "Installing Xcode Command Line Tools"
    xcode-select --install >/dev/null 2>&1 || true
    # Wait for install to complete
    while ! command -v git >/dev/null 2>&1; do
      log "Waiting for Xcode CLT installation..."
      sleep 5
    done
  fi
fi

log "✓ System prerequisites installed"

# ─────────────────────────────────────────────────────────────
# Set up basic shell configuration (standalone)
# ─────────────────────────────────────────────────────────────

log "Setting up basic shell environment"

# Ensure zsh is available
if ! need_cmd zsh; then
  log "ERROR: zsh installation failed"
  exit 1
fi

# Set zsh as default shell
ZSHPATH="$(command -v zsh)"
if [[ "$SHELL" != "$ZSHPATH" ]]; then
  log "Setting zsh as default shell"
  chsh -s "$ZSHPATH" "$USER" || true
fi

# Create basic shell config structure
mkdir -p "$HOME/.config/zsh"
mkdir -p "$HOME/.cache/zsh"

# Create basic zshrc if needed
if [[ ! -f "$HOME/.zshrc" ]]; then
  log "Creating basic .zshrc"
  cat > "$HOME/.zshrc" << 'ZSHRC'
# Basic zsh configuration
# Created by minimal.sh bootstrap

export HISTFILE="$HOME/.cache/zsh/history"
export HISTSIZE=10000
export SAVEHIST=10000

# Basic setup
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

# Basic aliases
alias ls='ls -G'
alias ll='ls -lG'

# Ensure .local/bin is in PATH
export PATH="$HOME/.local/bin:$PATH"

# Load basic environment if it exists
[[ -f "$HOME/.config/shell/env.sh" ]] && source "$HOME/.config/shell/env.sh"

ZSHRC
fi

# Create basic shell environment
mkdir -p "$HOME/.config/shell"
if [[ ! -f "$HOME/.config/shell/env.sh" ]]; then
  log "Creating basic shell environment"
  cat > "$HOME/.config/shell/env.sh" << 'ENVSH'
# Basic shell environment
# Created by minimal.sh bootstrap

export EDITOR="${EDITOR:-nano}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# Ensure .local/bin is in PATH
export PATH="$HOME/.local/bin:$PATH"

ENVSH
fi

# ─────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────

log "✓ Minimal bootstrap complete"
log ""
log "You now have:"
log "  • System prerequisites (git, curl, ca-certificates, zsh)"
log "  • Basic shell configuration"
log "  • Working zsh environment"
log ""
log "Next steps:"
log "  1. Start a new shell: exec zsh"
log "  2. For full setup with dotfiles, run: ./full.sh"
log ""
