#!/usr/bin/env bash
set -euo pipefail

# minimal.sh — Ultra-minimal creature comforts
# No dotfiles repo access. No chezmoi. No heavy system setup.
# Goal: get you a usable shell (zsh) + basics (git/curl) where possible.
#
# Generated from: dotfiles/scripts/templates/minimal.sh.template
# DO NOT EDIT THIS FILE DIRECTLY — edit the template in dotfiles repo

# --- Safety guards ------------------------------------------------------------

die() { echo "[minimal] ERROR: $*" >&2; exit 1; }
log() { printf "[minimal] %s\n" "$*"; }
need_cmd() { command -v "$1" >/dev/null 2>&1; }

log "Starting minimal bootstrap"

# Refuse to run as root (too easy to wreck a machine)
if [[ "${EUID:-$(id -u)}" -eq 0 ]]; then
  die "Don't run minimal.sh as root. Run as a normal user with sudo available."
fi

# Work in a temp dir for any future downloads/build steps
WORKDIR="$(mktemp -d 2>/dev/null || mktemp -d -t minimal-bootstrap)"
trap 'rm -rf "$WORKDIR"' EXIT

# ─────────────────────────────────────────────────────────────
# Detect OS
# ─────────────────────────────────────────────────────────────

case "$(uname -s)" in
  Darwin) OS="darwin" ;;
  Linux)  OS="linux"  ;;
  *)      echo "Unsupported OS" >&2; exit 1 ;;
esac

log "Detected OS: $OS"

# ─────────────────────────────────────────────────────────────
# Install system prerequisites
# ─────────────────────────────────────────────────────────────

log "Installing basic prerequisites (git, curl, zsh) when possible"

if [[ "$OS" == "linux" ]]; then
  if need_cmd apt-get; then
    log "Using apt-get"
    sudo apt-get update -y
    sudo apt-get install -y git curl ca-certificates zsh
  elif need_cmd dnf; then
    log "Using dnf"
    sudo dnf install -y git curl ca-certificates zsh
  elif need_cmd yum; then
    log "Using yum"
    sudo yum install -y git curl ca-certificates zsh
  elif need_cmd pacman; then
    log "Using pacman"
    sudo pacman -Sy --noconfirm git curl ca-certificates zsh
  else
    log "ERROR: No supported package manager found"
    log "Supported: apt-get, dnf, yum, pacman"
    exit 1
  fi
else
  # macOS: do not install Xcode CLT here (too heavy/interactive for “minimal”).
  # If git is missing, tell the user what to do.
  if ! need_cmd git; then
    log "git not found. Install Xcode Command Line Tools manually: xcode-select --install"
  fi
fi

log "✓ Prerequisites step complete"

# ─────────────────────────────────────────────────────────────
# Set up basic shell configuration (standalone)
# ─────────────────────────────────────────────────────────────

log "Setting up basic shell environment"

# Ensure zsh is available
if ! need_cmd zsh; then
  log "ERROR: zsh installation failed"
  exit 1
fi

# Do not force default shell changes in minimal; just tell the user.
ZSHPATH="$(command -v zsh)"
log "zsh available at: $ZSHPATH"
log "Tip: start zsh now with: exec zsh"

# Create basic shell config structure
mkdir -p "$HOME/.config/zsh"
mkdir -p "$HOME/.cache/zsh"

# Create basic zshrc if needed
if [[ ! -f "$HOME/.zshrc" ]]; then
  log "Creating basic .zshrc"
  cat > "$HOME/.zshrc" << 'ZSHRC'
# Basic zsh configuration
# Created by minimal.sh bootstrap

export HISTFILE="$HOME/.cache/zsh/history"
export HISTSIZE=10000
export SAVEHIST=10000

# Basic setup
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_SPACE

# Basic aliases (OS-aware)
if [[ "$OSTYPE" == darwin* ]]; then
  alias ls='ls -G'
  alias ll='ls -lG'
else
  alias ls='ls --color=auto'
  alias ll='ls -l --color=auto'
fi

# Ensure .local/bin is in PATH
export PATH="$HOME/.local/bin:$PATH"

# Load basic environment if it exists (prefer env.zsh, fall back to env.sh)
for f in "$HOME/.config/shell/env.zsh" "$HOME/.config/shell/env.sh"; do
  [[ -r "$f" ]] && source "$f" && break
done

# FZF Ctrl-R history search (only if fzf is installed)
if [[ -o interactive ]] && command -v fzf >/dev/null 2>&1; then
  fzf-history-widget() {
    local selected
    selected=$(fc -rl 1 | sed 's/^ *[0-9]\+ *//' | fzf --tac --no-sort --height=40% --layout=reverse 2>/dev/null) || return
    LBUFFER+="$selected"
  }
  zle -N fzf-history-widget
  bindkey '^R' fzf-history-widget
fi

ZSHRC
fi

# Create basic shell environment
mkdir -p "$HOME/.config/shell"
if [[ ! -f "$HOME/.config/shell/env.sh" && ! -f "$HOME/.config/shell/env.zsh" ]]; then
  log "Creating basic shell environment"
  cat > "$HOME/.config/shell/env.sh" << 'ENVSH'
# Basic shell environment
# Created by minimal.sh bootstrap

export EDITOR="${EDITOR:-nano}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-$HOME/.local/share}"
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-$HOME/.cache}"

# Ensure .local/bin is in PATH
export PATH="$HOME/.local/bin:$PATH"

ENVSH
  # Keep a zsh-friendly twin for setups that prefer env.zsh
  if [[ ! -f "$HOME/.config/shell/env.zsh" ]]; then
    cp "$HOME/.config/shell/env.sh" "$HOME/.config/shell/env.zsh"
  fi
fi

# ─────────────────────────────────────────────────────────────
# Summary
# ─────────────────────────────────────────────────────────────

log "✓ Minimal bootstrap complete"
log ""
log "You now have:"
log "  • System prerequisites (git, curl, ca-certificates, zsh)"
log "  • Basic shell configuration"
log "  • Working zsh environment"
log ""
log "Next steps:"
log "  1. Start a new shell: exec zsh"
log "  2. If you want your full dotfiles, use the full bootstrap flow (full.sh, not minimal.sh)."
log ""
